# -*- coding: utf-8 -*-
"""lab1_NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J85pBDxAlQKs5tShpLUEKeL4OIENz3Zx
"""



"""
**Business Case: AI Customer Complaint Triage Assistant**
Imagine an e-commerce company receives 5,000–10,000 customer complaints every day through email, chat and support tickets.

Examples:

"My order was supposed to arrive yesterday. Nobody is responding and I need it urgently."
"₹4,999 was deducted from my card but the order failed."
"The laptop I received has a broken screen. I want a replacement."

Today, support executives manually read each ticket and decide:
What is the problem? → How serious is it? → Which team should handle it? → What information should we capture? → What should we tell the customer?
Our LLM will automate the first-level analysis, not make irreversible business decisions.

| Stage | NLP task               | Business output                               |
| ----- | ---------------------- | --------------------------------------------- |
| 1     | Sentiment analysis     | Positive / Neutral / Negative                 |
| 2     | Classification         | Delivery / Refund / Payment / Product / Other |
| 3     | Information extraction | Order ID, product, amount, issue              |
| 4     | Summarization          | Short agent summary                           |
| 5     | Response generation    | Draft customer reply                          |
| 6     | Structured output      | JSON for CRM/helpdesk integration             |


CUSTOMER COMPLAINT <br>
        ↓ <br>
      LLM <br>
        ↓ <br>

 │ Sentiment           │ <br>
 │ Classification      │ <br>
 │ Information Extract │ <br>
 │ Summarization       │ <br>
 │ Response Generation │ <br>
        ↓ <br>
 STRUCTURED JSON <br>
        ↓ <br>
CRM / SUPPORT SYSTEM <br>
        ↓ <br>
Customer Support Agent <br>"""

#Part 1 — Setup in Google Colab
#We can use a small Hugging Face instruction model so we don't need an API key.

!pip install -q -U transformers accelerate torch
#It silently installs the Python libraries needed to load, run, and tokenize Hugging Face Transformer/LLM models efficiently

#Load Qwen
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2.5-1.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)

print("Qwen loaded successfully!")

"""What happened?

pipeline() gives us a simple Hugging Face interface.

Instruction-tuned model. It is designed to respond to instructions such as:

Classify this complaint...
Summarize this text...
Extract information...

So instead of training a model, we're going to instruct an existing model.
"""

# 3. Create a reusable Qwen function
def ask_qwen(prompt, max_new_tokens=200):

    messages = [
        {
            "role": "system",
            "content": "You are a helpful business AI assistant."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    model_inputs = tokenizer(
        [text],
        return_tensors="pt"
    ).to(model.device)

    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=max_new_tokens,
        do_sample=False
    )

    generated_ids = [
        output_ids[len(input_ids):]
        for input_ids, output_ids
        in zip(model_inputs.input_ids, generated_ids)
    ]

    response = tokenizer.batch_decode(
        generated_ids,
        skip_special_tokens=True
    )[0]

    return response

print(
    ask_qwen(
        "Explain artificial intelligence in one sentence."
    )
)

#4. Business Case: Customer Complaint Triage
#Create one customer ticket.
ticket = """
Customer Name: Rajesh Kumar
Order ID: ORD78291

I ordered an iPhone 17 for Rs. 82,000.

It was supposed to reach Hyderabad yesterday,
but I still haven't received it.

The tracking page hasn't updated for two days.

I need the phone urgently for a business trip.

Please resolve this immediately.
"""

#5. NLP Task 1 — Sentiment Analysis
#We are doing zero-shot classification. We did not train Qwen. We simply told it: Task + Possible labels + Input

prompt = f"""
Analyze the sentiment of the following customer complaint.

Choose exactly one:

Positive
Neutral
Negative

Customer complaint:

{ticket}

Return only the sentiment label.
"""

response = ask_qwen(prompt)

print("Category:",response)


#6. NLP Task 2 — Complaint Classification
prompt = f"""
Classify the following customer complaint.

Choose exactly one category:

Delivery
Refund
Payment
Product Defect
Cancellation
Other

Customer complaint:

{ticket}

Return only the category.
"""

response = ask_qwen(prompt)

print("Sentiment:",response)

#7. Few-Shot Classification (Examples)
prompt = f"""
You are a customer complaint classification system.

Examples:

Complaint:
My credit card was charged but the order failed.

Category:
Payment


Complaint:
The shoes arrived damaged.

Category:
Product Defect


Complaint:
I cancelled my order but still have not received my money.

Category:
Refund


Complaint:
My package was supposed to arrive yesterday but it has not arrived.

Category:
Delivery


Now classify the following complaint:

{ticket}

Choose from:

Delivery
Refund
Payment
Product Defect
Cancellation
Other

Return only the category.
"""

response = ask_qwen(prompt)

print("Few shot category:",response)

#8. NLP Task 3 — Information Extraction
#Now extract business information.

prompt = f"""
Extract information from the customer complaint.

Return the following fields:

Customer Name:
Order ID:
Product:
Amount:
Location:
Problem:

If information is unavailable,
write "Not Available".

Customer complaint:

{ticket}
"""

response = ask_qwen(prompt)

print("Information extraction:\n",response)

#9. NLP Task 4 — Summarization
prompt = f"""
You are assisting a customer-support executive.

Summarize the following customer complaint
in maximum 30 words.

Include:

1. Main problem
2. Product
3. Order ID
4. Customer urgency

Customer complaint:

{ticket}

Return only the summary.
"""

response = ask_qwen(
    prompt,
    max_new_tokens=80
)

print("Summarization:",response)

#10. NLP Task 5 — Response Generation

#10. NLP Task 5 — Response Generation
prompt = f"""
You are a professional customer-support executive
working for an e-commerce company.

Respond to the customer complaint below.

Requirements:

- Acknowledge the problem
- Be empathetic
- Mention the Order ID
- Mention that the delivery issue is being investigated
- Do not promise a specific delivery date
- Maintain a professional tone
- Maximum 100 words

Customer complaint:

{ticket}

Write the customer response.
"""

response = ask_qwen(
    prompt,
    max_new_tokens=180
)

print("Response Generation:\n",response)

#11. NLP Task 6 — Structured JSON Output
prompt = f"""
Analyze the following customer complaint.

Return ONLY valid JSON.

Use exactly this structure:

{{
    "customer_name": "",
    "order_id": "",
    "product": "",
    "amount": "",
    "location": "",
    "category": "",
    "sentiment": "",
    "priority": "",
    "summary": ""
}}

Category must be one of:

Delivery
Refund
Payment
Product Defect
Cancellation
Other

Sentiment must be one of:

Positive
Neutral
Negative

Priority must be one of:

Low
Medium
High

Customer complaint:

{ticket}

Return JSON only.
"""

response = ask_qwen(
    prompt,
    max_new_tokens=250
)

print(response)

#12. Convert the JSON response into Python
import json

prompt = f"""
Analyze the following customer complaint.

Return ONLY valid JSON.

{{
    "customer_name": "",
    "order_id": "",
    "category": "",
    "sentiment": "",
    "priority": ""
}}

Customer complaint:

{ticket}
"""

response = ask_qwen(
    prompt,
    max_new_tokens=150
)

print("Raw LLM Output:")
print(response)
import json

prompt = f"""
Analyze the following customer complaint.

Return ONLY valid JSON.

{{
    "customer_name": "",
    "order_id": "",
    "category": "",
    "sentiment": "",
    "priority": ""
}}

Customer complaint:

{ticket}
"""

response = ask_qwen(
    prompt,
    max_new_tokens=150
)

print("Raw LLM Output:")
print(response)

#13. Bad Prompt vs Good Prompt
bad_prompt = f"""
Analyze this:

{ticket}
"""

print(
    ask_qwen(
        bad_prompt,
        max_new_tokens=150
    )
)

good_prompt = f"""
You are a customer-support ticket analyst.

Analyze the following complaint.

Determine:

1. Complaint category
2. Sentiment
3. Priority
4. Main issue
5. Recommended support team

Complaint categories:

Delivery
Refund
Payment
Product Defect
Cancellation
Other

Priority:

Low
Medium
High

Return the result as a concise table.

Customer complaint:

{ticket}
"""

print(
    ask_qwen(
        good_prompt,
        max_new_tokens=200
    )
)

#14. Build One Complete AI Ticket Analyzer
def analyze_customer_ticket(ticket):

    prompt = f"""
You are an AI customer-support ticket analyst.

Analyze the following customer complaint.

Perform these tasks:

1. Identify complaint category
2. Determine sentiment
3. Determine priority
4. Identify main issue
5. Recommend the responsible team
6. Generate a short summary

Allowed categories:

Delivery
Refund
Payment
Product Defect
Cancellation
Other

Allowed sentiment:

Positive
Neutral
Negative

Allowed priority:

Low
Medium
High

Return ONLY valid JSON in the following format:

{{
    "category": "",
    "sentiment": "",
    "priority": "",
    "main_issue": "",
    "recommended_team": "",
    "summary": ""
}}

Customer complaint:

{ticket}
"""

    response = ask_qwen(
        prompt,
        max_new_tokens=250
    )

    return response


result = analyze_customer_ticket(ticket)

print(result)

#15. Test Different Customer Complaints
#Case 1 — Payment issue
ticket1 = """
My credit card has been charged Rs. 12,500
but the order was never created.

Please refund my money immediately.
"""

print(
    analyze_customer_ticket(ticket1)
)

#Case 2 — Product defect
ticket2 = """
The headphones I received today
are not working.

The left speaker has no sound.

I want a replacement.
"""

print(
    analyze_customer_ticket(ticket2)
)

#Case 3 — Delivery issue
ticket3 = """
My package was supposed to arrive three days ago.

Tracking still shows dispatched
and there has been no update.
"""

print(
    analyze_customer_ticket(ticket3)
)

#16. Analyze Multiple Tickets
tickets = [

"""
My order was supposed to arrive yesterday,
but it is still not delivered.
""",

"""
My credit card has been charged twice
for the same order.
""",

"""
The laptop I received has a cracked screen.
""",

"""
I cancelled my order five days ago
but haven't received my refund.
"""
]

#Process them
for i, customer_ticket in enumerate(tickets, start=1):

    print("=" * 50)
    print("TICKET:", i)

    result = analyze_customer_ticket(
        customer_ticket
    )

    print(result)

#17. Add Temperature for Prompt Experiments

def ask_qwen_creative(
    prompt,
    max_new_tokens=200,
    temperature=0.7
):

    messages = [
        {
            "role": "system",
            "content": "You are a helpful business AI assistant."
        },
        {
            "role": "user",
            "content": prompt
        }
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    model_inputs = tokenizer(
        [text],
        return_tensors="pt"
    ).to(model.device)

    generated_ids = model.generate(
        **model_inputs,
        max_new_tokens=max_new_tokens,
        do_sample=True,
        temperature=temperature,
        top_p=0.9
    )

    generated_ids = [
        output_ids[len(input_ids):]
        for input_ids, output_ids
        in zip(
            model_inputs.input_ids,
            generated_ids
        )
    ]

    response = tokenizer.batch_decode(
        generated_ids,
        skip_special_tokens=True
    )[0]

    return response

    #Compare 1
    print(
    ask_qwen_creative(
        prompt,
        temperature=0.9
    )
)

#option 2 compare
print(
    ask_qwen_creative(
        prompt,
        temperature=0.9
    )
)

"""Prompt Engineering <br>
      ↓ <br>
Works reasonably well <br>
      ↓ <br>
But output may vary <br>
      ↓ <br>
We want company-specific behaviour <br>
      ↓ <br>
PEFT <br>
      ↓ <br>
LoRA / QLoRA <br>
      ↓ <br>
Fine-tuned Qwen <br>
"""



